import React, { useState } from "react";
import { relativeTime } from "../../lib/utils.js";
import type { WolfData } from "../../hooks/useWolfData.js";

const CODE_EXTS = new Set([
  "ts", "tsx", "js", "jsx", "mjs", "cjs", "py", "rs", "go", "java", "rb", "php", "cs",
  "cpp", "cc", "c", "h", "hpp", "swift", "kt", "vue", "svelte", "json", "md", "mdx",
  "yml", "yaml", "toml", "css", "scss", "html", "sh", "sql", "prisma", "graphql",
]);
const PATH_RE = /([A-Za-z0-9_.\-/]+\.[A-Za-z][A-Za-z0-9]{0,7})/g;

// Render free text with file-path-looking tokens turned into buttons that jump to the
// Anatomy Browser filtered to that file. A token counts as a path if it contains a slash
// or ends in a known code extension (so "v1.10.0" or "99.9" stay plain text).
function linkifyPaths(text: string, onJump?: (file: string) => void): React.ReactNode {
  if (!onJump) return text;
  const out: React.ReactNode[] = [];
  let last = 0;
  let m: RegExpExecArray | null;
  PATH_RE.lastIndex = 0;
  while ((m = PATH_RE.exec(text)) !== null) {
    const token = m[1];
    const ext = token.slice(token.lastIndexOf(".") + 1).toLowerCase();
    const isPath = token.includes("/") || CODE_EXTS.has(ext);
    if (!isPath) continue;
    if (m.index > last) out.push(text.slice(last, m.index));
    out.push(
      <button
        key={`${m.index}-${token}`}
        onClick={() => onJump(token)}
        className="font-mono underline decoration-dotted underline-offset-2"
        style={{ color: "var(--accent)" }}
        title={`Jump to ${token} in Anatomy`}
      >{token}</button>
    );
    last = m.index + token.length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out.length ? out : text;
}

const sections = [
  { key: "achievements", title: "Achievements", icon: "🏆", color: "#059669" },
  { key: "improvements", title: "Improvements", icon: "✨", color: "#3b82f6" },
  { key: "next_tasks", title: "Next Tasks", icon: "📋", color: "#d97706" },
  { key: "risks", title: "Risks & Tech Debt", icon: "🛡", color: "#dc2626" },
] as const;

const PROMPT = `Analyze this project and write a JSON file to .wolf/suggestions.json with this exact structure:
{
  "generated_at": "<ISO timestamp>",
  "achievements": ["..."],
  "improvements": ["..."],
  "next_tasks": ["..."],
  "risks": ["..."]
}
Base it on the recent memory, anatomy, and current project state. Be specific and actionable.`;

export function AISuggestions({ data, onNavigate }: { data: WolfData; onNavigate?: (panel: string, params?: Record<string, string>) => void }) {
  const { suggestions } = data;
  const [copied, setCopied] = useState(false);
  const jumpToFile = onNavigate ? (file: string) => onNavigate("anatomy", { file }) : undefined;

  const copyPrompt = () => {
    navigator.clipboard.writeText(PROMPT).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (!suggestions) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <div className="text-4xl mb-3">✦</div>
        <h3 className="font-medium mb-2" style={{ color: "var(--text-secondary)" }}>No AI suggestions yet</h3>
        <p className="text-sm max-w-sm mb-6" style={{ color: "var(--text-muted)" }}>
          Suggestions are generated by Claude during your sessions. Paste this prompt into your next Claude Code conversation:
        </p>
        <div className="w-full max-w-lg text-left rounded-xl overflow-hidden" style={{ border: "1px solid var(--border-subtle)" }}>
          <div className="flex items-center justify-between px-4 py-2" style={{ background: "var(--bg-surface-hover)", borderBottom: "1px solid var(--border-subtle)" }}>
            <span className="text-xs font-medium" style={{ color: "var(--text-muted)" }}>Prompt for Claude</span>
            <button onClick={copyPrompt}
              className="text-xs px-3 py-1 rounded-md transition-colors"
              style={{ background: copied ? "var(--accent-subtle)" : "var(--bg-surface)", border: "1px solid var(--border-subtle)", color: copied ? "var(--accent)" : "var(--text-secondary)" }}
            >{copied ? "Copied!" : "Copy"}</button>
          </div>
          <pre className="text-xs px-4 py-3 whitespace-pre-wrap" style={{ background: "var(--bg-code)", color: "var(--text-secondary)" }}>{PROMPT}</pre>
        </div>
        <p className="text-xs mt-4" style={{ color: "var(--text-faint)" }}>
          Claude will write the results here automatically. They update live.
        </p>
      </div>
    );
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <span className="text-sm" style={{ color: "var(--text-faint)" }}>
          Generated: {suggestions.generated_at ? relativeTime(suggestions.generated_at) : "unknown"}
        </span>
        <button onClick={copyPrompt}
          className="px-3 py-1.5 text-xs rounded-lg transition-colors"
          style={{ background: "var(--bg-surface-hover)", border: "1px solid var(--border-subtle)", color: copied ? "var(--accent)" : "var(--text-secondary)" }}
        >{copied ? "Copied!" : "Regenerate via Claude"}</button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {sections.map(({ key, title, icon, color }) => {
          const items = suggestions[key] || [];
          return (
            <div key={key} className="rounded-xl p-5" style={{ background: `${color}08`, border: `1px solid ${color}33` }}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-lg">{icon}</span>
                <h3 className="font-medium" style={{ color }}>{title}</h3>
              </div>
              {items.length === 0 ? (
                <p className="text-sm" style={{ color: "var(--text-muted)" }}>None reported.</p>
              ) : (
                <ul className="space-y-2">
                  {items.map((item: string, i: number) => (
                    <li key={i} className="text-sm flex items-start gap-2" style={{ color: "var(--text-secondary)" }}>
                      <span className="mt-1 shrink-0" style={{ color: "var(--text-faint)" }}>•</span>
                      <span>{linkifyPaths(item, jumpToFile)}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
