// Builds `openwolf.mcpb` — a Claude Desktop / MCPB Desktop Extension that bundles `openwolf mcp`.
//
// The MCP server is dependency-free (only `node:` builtins), so esbuild emits ONE self-contained
// ESM file and the bundle carries no `node_modules`. Requires `pnpm build` first — we bundle from
// the compiled `dist/` (its `.js` relative imports resolve cleanly; bundling straight from `.ts`
// would not, since `.js` specifiers don't map back to `.ts`).
//
// Output: dist-mcpb/{manifest.json, server/index.mjs, openwolf.mcpb}. The .mcpb is a plain zip with
// manifest.json at the root — attach it to the GitHub Release so users install with one click.
import { build } from "esbuild";
import { readFileSync, writeFileSync, rmSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const serverEntry = path.join(root, "dist/src/mcp/server.js");

if (!existsSync(serverEntry)) {
  console.error("dist/src/mcp/server.js missing — run `pnpm build` first.");
  process.exit(1);
}

// Pull the tool list from the compiled server so the manifest never drifts from the real tools.
const { MCP_TOOLS } = await import(pathToFileURL(serverEntry).href);

const out = path.join(root, "dist-mcpb");
rmSync(out, { recursive: true, force: true });
mkdirSync(path.join(out, "server"), { recursive: true });

// A tiny entry that boots the stdio server for the user-selected project. Version is inlined at
// build time so the bundle has no way to disagree with package.json.
const stub =
  `import { runMcpStdio } from ${JSON.stringify(serverEntry)}\n` +
  `runMcpStdio({ projectDir: process.env.OPENWOLF_PROJECT_DIR || process.cwd(), version: ${JSON.stringify(pkg.version)} })\n`;

await build({
  stdin: { contents: stub, resolveDir: root, sourcefile: "mcpb-entry.mjs", loader: "js" },
  bundle: true,
  platform: "node", // node: builtins stay external automatically
  format: "esm",
  target: "node18",
  outfile: path.join(out, "server", "index.mjs"),
  banner: { js: "// OpenWolf MCPB bundle — generated by scripts/build-mcpb.mjs. Do not edit." },
});

// package.json `author` is a string ("Name <email> (url)"); MCPB wants an object with a name.
const am = /^([^<(]+?)\s*(?:<([^>]+)>)?\s*(?:\(([^)]+)\))?\s*$/.exec(pkg.author || "");
const author = { name: (am && am[1].trim()) || "Krynex Labs" };
if (am && am[2]) author.email = am[2];
if (am && am[3]) author.url = am[3];

const manifest = {
  manifest_version: "0.3",
  name: "openwolf",
  display_name: "OpenWolf",
  version: pkg.version,
  description:
    "Recall, resume digest, and native-memory health for an OpenWolf project — in Claude Desktop.",
  long_description:
    "Read-only access to an OpenWolf-managed project's cross-session knowledge from Claude Desktop " +
    "(and any other MCP client), where Claude Code's hook lifecycle doesn't exist. Three tools: " +
    "`openwolf_recall` keyword-searches the project's `.wolf/` knowledge (STATUS, cerebrum, memory, " +
    "buglog) and Claude's native Auto Memory; `openwolf_resume` returns the STATUS handoff digest; " +
    "`openwolf_memory_health` reports how much of the native memory actually loads at session start. " +
    "Everything is read-only and git-native — no database, no background worker.",
  author,
  homepage: pkg.homepage,
  documentation: pkg.homepage,
  repository: pkg.repository,
  license: pkg.license,
  keywords: ["openwolf", "memory", "context", "recall", "claude-code", "resume"],
  server: {
    type: "node",
    entry_point: "server/index.mjs",
    mcp_config: {
      command: "node",
      args: ["${__dirname}/server/index.mjs"],
      env: { OPENWOLF_PROJECT_DIR: "${user_config.project_dir}" },
    },
  },
  tools: MCP_TOOLS.map((t) => ({ name: t.name, description: t.description })),
  tools_generated: false,
  user_config: {
    project_dir: {
      type: "directory",
      title: "Project directory",
      description:
        "The OpenWolf-managed project whose .wolf/ knowledge and native Auto Memory to serve.",
      required: true,
    },
  },
  compatibility: {
    claude_desktop: ">=0.10.0",
    platforms: ["darwin", "win32", "linux"],
    runtimes: { node: ">=18.0.0" },
  },
};
writeFileSync(path.join(out, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

// Pack: .mcpb is a zip with manifest.json at the root. -X drops extra file attributes for a
// leaner, more reproducible archive.
const mcpbName = "openwolf.mcpb";
rmSync(path.join(out, mcpbName), { force: true });
execFileSync("zip", ["-r", "-q", "-X", mcpbName, "manifest.json", "server"], { cwd: out });

console.log(`Built dist-mcpb/${mcpbName} (v${pkg.version})`);
